name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "VISUALIZED_CODEBASE.svg"
          commit_message: "docs: update codebase diagram"
          excluded_paths: ".github"